extends: rpf_2d/base.yaml

model: gns
num_mp_steps: 10
latent_dim: 128
lr_start: 5.e-4

wandb: False
wandb_project: test_dump
# Change this with your own entity
wandb_entity: lagrangebench

noise_std: 0.0003
input_seq_length: 6 #to obtain 1 velocity 
loss_weight:
  acc: 1.0
log_steps: 1
eval_steps: 4